Repository sa7mon/S3Scanner, pull requests merged in 2023-09, with the labels that each got.

#197 Make region-client map concurrency safe
  provider/aws.go
  provider/clientmap/clientmap.go
  provider/custom.go
  provider/digitalocean.go
  provider/dreamhost.go
  provider/gcp.go
  provider/linode.go
  provider/providers.go
Labels: refactor

#205 feat: add region check
  .github/workflows/check-regions.yml
  Makefile
  cmd/regioncheck/regioncheck.go
  cmd/regioncheck/regioncheck_test.go
  collection/collection.go
  go.mod
  go.sum
  provider/digitalocean.go
  provider/dreamhost.go
  provider/linode.go
  provider/providers.go
Labels: feature

#211 bugfix: remove dreamhost region check
  cmd/regioncheck/regioncheck.go
  cmd/regioncheck/regioncheck_test.go
  provider/providers_test.go
Labels: bug

#210 feat: add scaleway support
  cmd/regioncheck/regioncheck.go
  cmd/regioncheck/regioncheck_test.go
  provider/providers.go
  provider/providers_test.go
  provider/scaleway.go
Labels: new-provider

#212 feat: add winget package
  .github/workflows/winget-release.yml
  README.md
Labels: packaging

#215 dev: add mitmproxy
  .dev/docker-compose.yml
  .dev/entrypoint.sh
  Makefile
  README.md
Labels: refactor

#228 chore: update gh workflows
  .github/workflows/release.yml
  .github/workflows/winget-release.yml
Labels: packaging

#229 chore: ignore aws library patch releases
  .github/dependabot.yml
Labels: dependencies
